FROM ubuntu:latest
SHELL ["/bin/bash", "-c"]
ENV LC_CTYPE=C.UTF-8
RUN apt-get -y update
RUN apt-get -y install git python3 curl python3-pip flex bison vim tmux wget zsh sudo cmake libssl-dev psmisc htop file bat  psmisc
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 100

RUN git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
ENV PATH="/depot_tools:$PATH"
RUN fetch v8
WORKDIR /v8
RUN gclient sync



RUN wget https://apt.llvm.org/llvm.sh
RUN chmod +x llvm.sh
RUN  ./llvm.sh 20

RUN ln -s /usr/bin/clang-20 /usr/bin/clang
RUN ln -s /usr/bin/clang++-20 /usr/bin/clang++
RUN ln -s /usr/bin/llvm-config-20 /usr/bin/llvm-config
